name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        
        # Replace remote URL with SSH URL
        git remote set-url origin git@github.com:Nik-luftmensch/nik-luftmensch.github.io.git
        
        # Create or update gh-pages branch
        if [ "$(git branch --list gh-pages)" ]; then
          git checkout gh-pages
        else
          git checkout --orphan gh-pages
        fi
        
        git rm -rf .
        git checkout main -- .
        git add .
        git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"
        git push origin gh-pages --force
